<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>マルチメディア質問サービス：疑問丸</title>

    <link href="http://www.css-reset.com/css/meyer.css" media="screen, projection" rel="stylesheet" type="text/css" />
    
    <!-- Bootstrap -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <link href="/css/justified-nav.css" rel="stylesheet">

    <link href="/css/style.css" rel="stylesheet">
    
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">

      <!-- The justified navigation menu is meant for single line per list item.
           Multiple lines will require custom code not provided by Bootstrap. -->
      <div class="masthead">
        <h3 class="text-muted"><img src="/css/icon.png"/>マルチメディア質問サービス 質問丸</h3>
    　　</div>

      <!-- Jumbotron -->
      <div class="jumbotron">
        <h1><img src="/css/icon.png"/>Answers</h1>
        <p class="lead">質問に様々な回答がされています。ぜひあなたも質問に答えて下さい！</p>
        <h2>質問番号：<?php echo $this->question_id; ?></h2>
        <div class="row">
          <div class="col-lg-12">
            <img src="/<?php echo $this->src; ?>" />
          </div>
        </div>
      </div>

      <div class="row"> 
        <div class="col-lg-4">
          <h2>関連書籍</h2>
        </div>
      </div>

      <div class="row">
        <?php foreach($this->books['Items'] as $book) :?>
        <div class="col-sm-4 col-lg-4 col-md-4">
          <div class="thumbnail">
              <img src="<?php echo $book['mediumImageUrl']; ?>" alt="">
              <div class="caption">
                  <h4 style="min-height:80px;"><a href="<?php echo $book['itemUrl']; ?>"><?php echo $book['title']; ?></a></h4>
                  <h4>&yen;<?php echo number_format($book['itemPrice']); ?></h4>
              </div>
              <div class="ratings">
                  <p class="pull-right"><?php echo $book['reviewCount']; ?> reviews</p>
                  <p>
                      <?php for($i = 0; $i <= $book['reviewAverage']; $i++) :?>
                      <span class="glyphicon glyphicon-star"></span>
                      <?php endfor; ?>
                  </p>
              </div>
          </div>
        </div>
        <?php endforeach; ?>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="col-lg-4">
          <h2>ご利用上の注意</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          
        </div>
        <div class="col-lg-4">
          <h2>運営元</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          
       </div>
        <div class="col-lg-4">
          <h2>お問い合わせ</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
          
        </div>
      </div>

      <!-- Site footer -->
      <footer class="footer">
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/photobooth_min.js"></script>
    <script src="/js/script.js"></script>
  </body>
</html>